---
name: ci

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  push:
    uses: ./.github/workflows/push.yml
    secrets:
      # Secrets seem to be isolated, but if the reusable workflow also
      # triggers on anything in addition to workflow_call, the input secret
      # needs to have the same name.
      PUSH_TO_OTHER_REPO_PRIVATE_KEY: ${{ secrets.PUSH_TO_OTHER_REPO_PRIVATE_KEY }}
  all:
    needs: [push]
    runs-on: ubuntu-22.04
    steps:
      - name: Success
        run: "true"
